# This is a basic workflow to help you get started with Actions

name: Jekyll Build Checker

on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: jekyll/jekyll
    steps:
    - uses: actions/checkout@v2
      
    - name: Run a multi-line script
      run: |
        bundle install
        jekyll build
